version: '3'

services:
  spring-spotify-boot:
    image: spring-spotify-boot:latest
    ports:
      - 7001:7001
  spring-boot-docker:
    image: spring-boot-docker:latest
    ports:
      - 8484:8080
