apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-kube
spec:
  selector:
    matchLabels:
      app: spring-kube
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-kube
    spec:
      containers:
        - name: spring-kube
          image: techmomo/spring-kubernetes:v1
          ports:
            - containerPort: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: spring-kube
spec:
  selector:
    app: spring-kube
  ports:
    - port: 8181
      targetPort: 8181
  type: LoadBalancer
