spring:
  application:
    name: zuul-gateway

server:
    port: 8073

zuul:
  ignoredServices: '*'
  routes:
    hello-service:
      path: /helloService/**
      url: http://localhost:8111/helloService/
      stripPrefix: false
eureka:
    instance:
           preferIpAddress: false
    client:
           registerWithEureka: true
           fetchRegistry: true
           serviceUrl:
              defaultZone: http://localhost:8761/eureka/
